version: '3'

services:
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  hub:
    image: "home-automation-hub"
    ports:
      - "5000:5000"
      - "5001:5001"

volumes:
  redis-data: